package utils

/*
  Status:
	1 成功
	0 失败
	2.. 文章相关错误
	3.. 用户相关错误
 */
const (
	SUCCESS = 1
	ERROR 	= 0
	NO_POWER = 2
	SYSTEM_ERROR = 3

	//文章

	ERROR_AUTHOR_ID_NOT_EXIST 	= 2001
	ERROR_AUTHOR_ID_NOT_NULL 	= 2002
	ERROR_POST_ID_NOT_EXIST 	= 2003
	ERROR_POST_ID_NOT_NULL 		= 2004
	ERROR_POST_TITLE_NOT_NULL 	= 2005

	//用户
	ERROR_USERID_NOT_EXIST 		= 3010
	ERROR_USERID_WRONG			= 3011
	ERROR_USERID_TYPE_WRONG		= 3012
	ERROR_USERNAME_TYPE_WRONG	= 3020
	ERROR_USERNAME_NOT_EXIST	= 3021
	ERROR_USERNAME_EXIST		= 3022
	ERROR_USERNAME_NOT_NULL		= 3023
	ERROR_USERNAME_WRONG		= 3024
	ERROR_NICKNAME_TYPE_WRONG	= 3030
	ERROR_NICKNAME_NOT_EXIST	= 3031
	ERROR_NICKNAME_EXIST		= 3032
	ERROR_NICKNAME_NOT_NULL		= 3033
	ERROR_NICKNAME_WRONG		= 3034
	ERROR_MAIL_TYPE_WRONG		= 3040
	ERROR_MAIL_NOT_EXIST		= 3041
	ERROR_MAIL_EXIST			= 3042
	ERROR_MAIL_NOT_NULL			= 3043
	ERROR_MAIL_WRONG			= 3044
	ERROR_ROLE_TYPE_WRONG		= 3050
	ERROR_ROLE_WRONG			= 3051
	ERROR_ROLE_NOT_NULL			= 3052
	ERROR_PASSWORD_TYPE_WRONG	= 3060
	ERROR_PASSWORD_WRONG		= 3061
	ERROR_PASSWORD_NOT_NULL		= 3062
	ERROR_PAGESIZE_TYPE_WRONG	= 3070
	ERROR_PAGESIZE_NOT_NULL		= 3071
	ERROR_PAGENUM_TYPE_WRONG	= 3072
	ERROR_PAGENUM_NOT_NULL		= 3073
	ERROR_TOKEN_NOT_EXIST 		= 3080
	ERROR_TOKEN_RUNTIME 		= 3081
	ERROR_TOKEN_TYPE_WRONG 		= 3082
	ERROR_TOKEN_WRONG 			= 3083


	//数据库
	ERROR_DATABASE_WRITE		= 4001
	ERROR_DATABASE_SEARCH		= 4002
	ERROR_DATABASE_DELETE		= 4003
)

var errorStatus = map[int]string{
	SUCCESS : "OK",
	ERROR : "FAILED",
	SYSTEM_ERROR : "系统错误",
	NO_POWER: "没有权限",

	ERROR_AUTHOR_ID_NOT_EXIST : "作者ID不存在",
	ERROR_AUTHOR_ID_NOT_NULL : "作者ID不能为空",
	ERROR_POST_ID_NOT_EXIST : "文章ID不存在",
	ERROR_POST_ID_NOT_NULL : "文章ID不能为空",
	ERROR_POST_TITLE_NOT_NULL : "文章标题不能为空",

	ERROR_USERID_NOT_EXIST : "用户ID不存在",
	ERROR_USERID_WRONG : "用户ID错误",
	ERROR_USERID_TYPE_WRONG : "用户ID不合法",
	ERROR_USERNAME_TYPE_WRONG : "用户名不合法",
	ERROR_USERNAME_NOT_EXIST : "用户名不存在",
	ERROR_USERNAME_EXIST : "用户名已存在",
	ERROR_USERNAME_NOT_NULL : "用户名不能为空",
	ERROR_USERNAME_WRONG : "用户名错误",
	ERROR_NICKNAME_TYPE_WRONG : "昵称不合法",
	ERROR_NICKNAME_NOT_EXIST : "昵称不存在",
	ERROR_NICKNAME_EXIST : "昵称已存在",
	ERROR_NICKNAME_NOT_NULL : "昵称不能为空",
	ERROR_NICKNAME_WRONG : "昵称错误",
	ERROR_MAIL_TYPE_WRONG : "邮箱不合法",
	ERROR_MAIL_NOT_EXIST : "邮箱不存在",
	ERROR_MAIL_EXIST : "邮箱已存在",
	ERROR_MAIL_NOT_NULL : "邮箱不能为空",
	ERROR_MAIL_WRONG : "邮箱错误",
	ERROR_ROLE_TYPE_WRONG : "用户类型不合法",
	ERROR_ROLE_WRONG : "用户类型错误",
	ERROR_ROLE_NOT_NULL : "用户类型不能为空",
	ERROR_PASSWORD_TYPE_WRONG : "密码不合法",
	ERROR_PASSWORD_WRONG : "密码错误",
	ERROR_PASSWORD_NOT_NULL : "密码不能为空",
	ERROR_PAGESIZE_TYPE_WRONG : "分页大小不合法",
	ERROR_PAGESIZE_NOT_NULL : "分页大小不能为空",
	ERROR_PAGENUM_TYPE_WRONG : "分页位置不合法",
	ERROR_PAGENUM_NOT_NULL : "分页位置不能为空",
	ERROR_TOKEN_NOT_EXIST : "TOKEN不存在",
	ERROR_TOKEN_RUNTIME : "TOKEN已过期",
	ERROR_TOKEN_TYPE_WRONG : "TOKEN格式错误",
	ERROR_TOKEN_WRONG : "TOKEN错误",

	ERROR_DATABASE_WRITE :  "数据库写入失败",
	ERROR_DATABASE_SEARCH : "数据库查询失败",
	ERROR_DATABASE_DELETE : "数据库删除失败",
}

//获取错误异常

func GetErrorMessage(status int) string {
	return errorStatus[status]
}
